### PR TITLE
Added user search function on User Management Page

### LINKED ISSUE #73: Need a search function for users
There are more than 100 users registered and need to search function for users. Better if we can search with login.

### PR DESCRIPTION
**Pull request by coma123**
Fix #73

## Type of change

Please delete options that are not relevant.

- Added search input on User Management page
- Added filter functionality when loading users

### CODE REVIEW

**Comment by SudharakaP** [comment]
@coma123 : Hi Omari; thanks much for your contribution; yours is our first pull request 😄 

The Travis test seems to be failing and I think it's because the unit test is not modified to align with the new code. Would you be able to make this modification to get the tests working as well? Let me know if you have any questions 😄

**Comment by coma123** [comment]
Hi, @SudharakaP I am glad that my contribution is first to this project. Hope that will take luck for it :smile: 
Errors fixed as I think, passed all unit test in my local environment.

**Comment by SudharakaP** [comment]
@coma123 : Thanks for the change and fixing the unit tests accordingly. The reason that it is failing now is because Sonar doesn't support analysis on PRs (unless you have the [developer edition](https://docs.sonarqube.org/latest/analysis/pull-request/); we have the community edition). We have to change the Travis script so that pull requests are not considered for Sonar analysis. I'll do that soon and get back to you. 😄 

But as far as I can see your code looks good and when the Sonar issue is fixed it should be good to go. Thanks much for contributing; please feel free to contribute more to the repo and if you have any questions or ideas feel free to create an issue. Our goal is to make this a fully fledged open source course management system; there's lots more to add in that regard. 😄

**Comment by coma123** [comment]
> @coma123 : Thanks for the change and fixing the unit tests accordingly. The reason that it is failing now is because Sonar doesn't support analysis on PRs (it's only supported in the [developer edition](https://docs.sonarqube.org/latest/analysis/pull-request/)). We have to change the Travis script so that pull requests are not considered for Sonar analysis. I'll do that soon and get back to you. 
> 
> But as far as I can see your code looks good and when the Sonar issue is fixed it should be good to go. Thanks much for contributing; please feel free to contribute more to the repo and if you have any questions or ideas feel free to create an issue. Our goal is to make this a fully fledged open source course management system; there's lots more to add in that regard.

Did it, commented part of script in .travis.yml

Will try to find time and contribute to this project as much as I can.

Thanks and good luck on this journey :+1: :+1:

**Comment by SudharakaP** [comment]
@coma123 : Could you please revert the last commit since that cannot go to the development branch; it's only good for you to test that the Travis build works but if it goes to development the sonar analysis will not run for all the commits. 😄

**Comment by coma123** [comment]
> @coma123 : Could you please revert the last commit since that cannot go to the development branch; it's only good for you to test that the Travis build works but if it goes to development the sonar analysis will not run for all the commits.

@SudharakaP reverted

**Comment by SudharakaP** [comment]
I am merging this since we need this functionality soon; hopefully next time onwards we will have #75 fixed so that the Sonar analysis could be correctly run. 😄

**Comment by SudharakaP** [comment]
@coma123 : Just to let you know I've added a change (#75) to make sure Sonar is only executed on the develop branch. We will not see the problem you encountered in your PR request. Sonar analysis results will be added as comments for PRs. 

Related Issue: #75

**Comment by coma123** [comment]
> comments

Great 👍 👍 will be more easy in future for any other contributor too.

**Pull request merged**
